
### REGISTER NEW USER - WORKS

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "ela12345",
  "email": "ela12345@gmail.com",
  "password": "12345"
}

### LOGIN NEW USER

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "ela12345",
  "email": "ela12345@gmail.com",
  "password": "12345"
}



### GET USER PROFILE - WORK only with valid token
GET http://localhost:3000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwidXNlcm5hbWUiOiJlbGExMjM0NSIsImVtYWlsIjoiZWxhMTIzNDVAZ21haWwuY29tIiwiaWF0IjoxNzY4Mjk2NDM4LCJleHAiOjE3Njg5MDEyMzh9.jZB3X27qg7muyxsW3EiKJDCd50qlBvhOuybr4WY4J78
### LOGOUT USER
POST http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsInVzZXJuYW1lIjoiZWxhMTIzNDUiLCJlbWFpbCI6ImVsYTEyMzQ1QGdtYWlsLmNvbSIsImlhdCI6MTc2ODI5NjU0NSwiZXhwIjoxNzY4OTAxMzQ1fQ.xQ934UaiKY_wtvCmYkeh0sbvFMhwibZIzcFD3wJzgiE
### DELETE USER
DELETE http://localhost:3000/api/auth/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwidXNlcm5hbWUiOiJlbGExMjM0NSIsImVtYWlsIjoiZWxhMTIzNDVAZ21haWwuY29tIiwiaWF0IjoxNzY4Mjk2NDM4LCJleHAiOjE3Njg5MDEyMzh9.jZB3X27qg7muyxsW3EiKJDCd50qlBvhOuybr4WY4J78