
### REGISTER NEW USER - WORKS

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "shaked",
  "email": "shaked@gmail.com",
  "password": "12345"
}

### LOGIN NEW USER

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "shaked",
  "email": "shaked@gmail.com",
  "password": "12345"
}



### GET USER PROFILE - WORK only with valid token
GET http://localhost:3000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Njc5ZGQwMzRmZTM2MGQ5ZTRjZmMzMiIsInVzZXJuYW1lIjoic2hha2VkMSIsImVtYWlsIjoic2hha2VkMUBnbWFpbC5jb20iLCJpYXQiOjE3NjgzOTkwMTQsImV4cCI6MTc2OTAwMzgxNH0.H5ocsGkWkzePBWsCTduHppZAQ43LFloD0V52XsdgzcU
### LOGOUT USER
POST http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Njc5ZGQwMzRmZTM2MGQ5ZTRjZmMzMiIsInVzZXJuYW1lIjoic2hha2VkMSIsImVtYWlsIjoic2hha2VkMUBnbWFpbC5jb20iLCJpYXQiOjE3NjgzOTg3NjgsImV4cCI6MTc2OTAwMzU2OH0.6wCiIZf2g_rwsHvjd_UikzDGdyUCb1geA28_dZL0fLY

### DELETE USER
DELETE http://localhost:3000/api/auth/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Njc5ZGQwMzRmZTM2MGQ5ZTRjZmMzMiIsInVzZXJuYW1lIjoic2hha2VkMSIsImVtYWlsIjoic2hha2VkMUBnbWFpbC5jb20iLCJpYXQiOjE3NjgzOTg3NjgsImV4cCI6MTc2OTAwMzU2OH0.6wCiIZf2g_rwsHvjd_UikzDGdyUCb1geA28_dZL0fLY

### CHECK LEECHES API CONNECTion
GET https://lichess.org/api/account
Authorization: Bearer lip_qvg5p6w3kqLVWiwTYy1z


### REGISTER NEW USER ON LICHESS
POST https://lichess.org/api/user
Authorization: Bearer lip_qvg5p6w3kqLVWiwTYy1z
Content-Type: application/json

{
  "username": "mevo",
  "email": "mevo@gmail.com",
  "password": "12345"
}



### CREATE NEW LICHESS GAME
POST http://localhost:3000/api/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NjdjMTUxNzU2Y2NmMGFmNTMzN2MxMiIsInVzZXJuYW1lIjoic2hha2VkIiwiZW1haWwiOiJzaGFrZWRAZ21haWwuY29tIiwiaWF0IjoxNzY4NDA3NDAwLCJleHAiOjE3NjkwMTIyMDB9.2528VnIkiiaV6VUye3gm5knmxB3W_iHxre176EH9Iv0
Content-Type: application/json

{
  "externalApi": "https://lichess.org/@/mevo0108",
  "players": ["user1", "user2"]
}